# .github/PULL_REQUEST_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature
    url: https://github.com/tolastarras/path-adventure/issues/new?template=feature.md
    about: Add a new feature or enhancement
  - name: ğŸ› Bug Fix
    url: https://github.com/tolastarras/path-adventure/issues/new?template=bug-fix.md
    about: Fix a bug or issue